# Generated by Django 6.0.6 on 2026-07-19 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveSmallIntegerField()),
                ('defender_card', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win_condition', models.CharField(choices=[('HIGH', '높은 숫자 승리'), ('LOW', '낮은 숫자 승리')], max_length=10)),
                ('status', models.CharField(choices=[('WAITING', '반격 대기중'), ('FINISHED', '종료')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_games', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
